const FETCH_EMPLOYMENTS = 'APP/EMPLOYMENTS/FETCH_EMPLOYMENTS'
const ADD_EMPLOYMENT = 'APP/EMPLOYMENTS/ADD_EMPLOYMENTS'
const DELETE_EMPLOYMENT = 'APP/EMPLOYMENTS/DELETE_EMPLOYMENTS'
const PUT_EMPLOYMENT = 'APP/EMPLOYMENTS/PUT_EMPLOYMENTS'


export const FETCH_EMPLOYMENTS_REQUEST = `${FETCH_EMPLOYMENTS}_REQUEST`
export const FETCH_EMPLOYMENTS_SUCCESS = `${FETCH_EMPLOYMENTS}_SUCCESS`
export const FETCH_EMPLOYMENTS_FAILURE = `${FETCH_EMPLOYMENTS}_FAILURE`

export const DELETE_EMPLOYMENTS_REQUEST = `${DELETE_EMPLOYMENT}_REQUEST`
export const DELETE_EMPLOYMENTS_SUCCESS = `${DELETE_EMPLOYMENT}_SUCCESS`
export const DELETE_EMPLOYMENTS_FAILURE = `${DELETE_EMPLOYMENT}_FAILURE`

export const ADD_EMPLOYMENTS_REQUEST = `${ADD_EMPLOYMENT}_REQUEST`
export const ADD_EMPLOYMENTS_SUCCESS = `${ADD_EMPLOYMENT}_SUCCESS`
export const ADD_EMPLOYMENTS_FAILURE = `${ADD_EMPLOYMENT}_FAILURE`

export const PUT_EMPLOYMENT_REQUEST = `${PUT_EMPLOYMENT}_REQUEST`
export const PUT_EMPLOYMENT_SUCCESS = `${PUT_EMPLOYMENT}_SUCCESS`
export const PUT_EMPLOYMENT_FAILURE = `${PUT_EMPLOYMENT}_FAILURE`

export const CLEAR_ERROR = "CLEAR_ERROR"

export const BaseApi = "https://my-json-server.typicode.com/shahraZd/fakeServerGmc"